# Generated by Django 5.1.1 on 2024-09-24 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('sepal_width', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('petal_length', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('petal_width', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('species', models.CharField(max_length=15)),
            ],
        ),
    ]
